@extends('layouts.admin.app')
@section('title', $title)
@section('content')
<div class="page-header d-print-none"><div class="row g-2 align-items-center"><div class="col"><div class="page-pretitle">System</div><h2 class="page-title">{{ $title }}</h2><div class="text-secondary mt-1">{{ $description }}</div></div></div></div>
<div class="card mb-3"><div class="card-body py-2"><div class="nav nav-pills">@foreach ($tabs as $tab => $label)<a href="{{ route('admin.system.system-operations.index', ['view' => $tab]) }}" class="nav-link {{ $currentTab === $tab ? 'active' : '' }}">{{ $label }}</a>@endforeach</div></div></div>
<div class="row row-cards">
<div class="col-lg-6"><div class="card h-100"><div class="card-header"><h3 class="card-title">Health check</h3><span class="badge admin-status admin-status-{{ $health['status'] }} ms-auto">{{ str($health['status'])->title() }}</span></div><div class="card-body">@foreach ($health['checks'] as $check => $ok)<div class="d-flex align-items-center py-2 border-bottom"><span>{{ str($check)->replace('_',' ')->title() }}</span><span class="ms-auto badge {{ $ok ? 'bg-green-lt text-green' : 'bg-red-lt text-red' }}">{{ $ok ? 'OK' : 'Failed' }}</span></div>@endforeach</div></div></div>
<div class="col-lg-6"><div class="card h-100"><div class="card-header"><h3 class="card-title">Readiness</h3><span class="badge {{ $readiness['ready'] ? 'bg-green-lt text-green' : 'bg-yellow-lt text-yellow' }} ms-auto">{{ $readiness['ready'] ? 'Ready' : 'Not ready' }}</span></div><div class="card-body"><div class="h3 mb-1">{{ $health['application']['name'] }}</div><div class="text-secondary mb-4">{{ $health['application']['environment'] }} · {{ $health['application']['version'] }}</div><div class="subheader mb-2">Pending migrations</div>@forelse ($readiness['pending_migrations'] as $migration)<div class="font-monospace small mb-1">{{ $migration }}</div>@empty<div class="text-green">No pending migrations</div>@endforelse</div></div></div>
<div class="col-12"><div class="card"><div class="card-header"><h3 class="card-title">Safe maintenance actions</h3></div><div class="card-body"><div class="row g-3">@foreach ([['health-check','Run health check','primary'],['readiness-check','Run readiness check','primary'],['clear-cache','Clear application cache','warning'],['queue-restart','Restart queue workers','warning']] as [$action,$label,$tone])<div class="col-md-6 col-xl-3"><form method="POST" action="{{ route('admin.system.system-operations.page-action', ['view' => 'health']) }}" onsubmit="return confirm('Run this maintenance action?')">@csrf<input type="hidden" name="action" value="{{ $action }}"><button type="submit" class="btn btn-{{ $tone }} w-100">{{ $label }}</button></form></div>@endforeach</div><hr><form method="POST" action="{{ route('admin.system.system-operations.page-action', ['view' => 'health']) }}" class="row g-2 align-items-end">@csrf<input type="hidden" name="action" value="flag-stuck-orders"><div class="col-sm-4"><label class="form-label">Stuck threshold in minutes</label><input type="number" name="minutes" value="60" min="15" class="form-control"></div><div class="col-sm-auto"><button type="submit" class="btn btn-outline-danger">Flag stuck orders</button></div></form></div></div></div>
</div>
@endsection
