@extends('layouts.seller.app')
@section('title', $title)
@section('content')
@php
    $view = $view ?? 'default'; $stats=$stats??[]; $filters=$filters??[]; $tabs=$tabs??[]; $pageActions=$pageActions??[]; $canCreate=$canCreate??false;
    $routeParams = $view === 'default' ? [] : ['view'=>$view];
@endphp
<div class="page-header d-print-none mb-3"><div class="row g-2 align-items-center"><div class="col"><div class="page-pretitle">Seller Operations</div><h2 class="page-title">{{ $title }}</h2><div class="text-secondary mt-1">{{ $description }}</div></div><div class="col-auto ms-auto"><div class="btn-list">
@if($canCreate)<a href="{{ route('seller.resource.'.$module.'.create',$routeParams) }}" class="btn btn-success">+ Create</a>@endif
</div></div></div></div>
@if($tabs!==[])<div class="card mb-3"><div class="card-body py-2"><div class="nav nav-pills">@foreach($tabs as $tab=>$label)<a href="{{ route('seller.resource.'.$module.'.index',['view'=>$tab]) }}" class="nav-link {{ $view===$tab?'active':'' }}">{{ $label }}</a>@endforeach</div></div></div>@endif
@if($stats!==[])<div class="row row-cards mb-3">@foreach($stats as $label=>$value)<div class="col-sm-6 col-lg-3"><div class="card card-sm seller-stat-card"><div class="card-body"><div class="subheader">{{ $label }}</div><div class="h2 mb-0">{{ $value }}</div></div></div></div>@endforeach</div>@endif
@foreach($pageActions as $pageAction)
<div class="card seller-action-card mb-3"><div class="card-header"><h3 class="card-title">{{ $pageAction['label'] }}</h3></div><form method="POST" action="{{ route('seller.resource.'.$module.'.page-action',$routeParams) }}" enctype="multipart/form-data">@csrf<div class="card-body"><div class="row g-3">@foreach($pageAction['fields']??[] as $field)<div class="{{ ($field['type']??'')==='hidden'?'d-none':'col-md-4' }}">@include('seller.manage._field',['field'=>$field])</div>@endforeach</div></div><div class="card-footer text-end"><button class="btn btn-{{ $pageAction['tone']??'primary' }}">{{ $pageAction['label'] }}</button></div></form></div>
@endforeach
<div class="card"><div class="card-header"><form method="GET" action="{{ route('seller.resource.'.$module.'.index') }}" class="row g-2 w-100 align-items-end">@if($view!=='default')<input type="hidden" name="view" value="{{ $view }}">@endif
@foreach($filters as $filter)<div class="col-sm-6 col-lg-auto"><label class="form-label">{{ $filter['label'] }}</label>@if(($filter['type']??'text')==='select')<select name="{{ $filter['name'] }}" class="form-select form-select-sm"><option value="">All</option>@foreach($filter['options'] as $key=>$label)<option value="{{ $key }}" @selected((string)request($filter['name'])===(string)$key)>{{ $label }}</option>@endforeach</select>@elseif(($filter['type']??'text')==='checkbox')<label class="form-check"><input class="form-check-input" type="checkbox" name="{{ $filter['name'] }}" value="1" @checked(request()->boolean($filter['name']))><span class="form-check-label">Yes</span></label>@else<input type="search" name="{{ $filter['name'] }}" value="{{ request($filter['name']) }}" class="form-control form-control-sm" placeholder="{{ $filter['placeholder']??'' }}">@endif</div>@endforeach
<div class="col-sm-4 col-lg-auto"><label class="form-label">Rows</label><select name="per_page" class="form-select form-select-sm">@foreach([20,50,100] as $size)<option value="{{ $size }}" @selected((int)request('per_page',20)===$size)>{{ $size }}</option>@endforeach</select></div><div class="col-sm-auto"><button class="btn btn-success btn-sm">Apply filters</button><a href="{{ route('seller.resource.'.$module.'.index',$routeParams) }}" class="btn btn-outline-secondary btn-sm">Reset</a></div></form></div>
<div class="table-responsive"><table class="table card-table table-vcenter table-hover"><thead><tr>@foreach($columns as $column)<th>{{ $column }}</th>@endforeach<th class="w-1"></th></tr></thead><tbody>@forelse($rows as $row)<tr>@foreach($row['cells'] as $cell)<td>@php($normalized=strtolower((string)$cell))@if(in_array($normalized,['active','approved','completed','online','published','fulfilled','read','settled','ready for pickup']))<span class="badge bg-green-lt">{{ str($cell)->replace('_',' ')->title() }}</span>@elseif(in_array($normalized,['pending','pending_approval','unsettled','processing','preparing','awaiting_store_response','unread','requested']))<span class="badge bg-yellow-lt">{{ str($cell)->replace('_',' ')->title() }}</span>@elseif(in_array($normalized,['rejected','failed','cancelled','inactive','offline','hidden','seller_rejected','rejected_by_seller']))<span class="badge bg-red-lt">{{ str($cell)->replace('_',' ')->title() }}</span>@else{{ $cell }}@endif</td>@endforeach<td><div class="btn-list flex-nowrap"><a href="{{ route('seller.resource.'.$module.'.show',array_merge(['id'=>$row['id']],$routeParams)) }}" class="btn btn-sm btn-outline-primary">View</a>@if($row['editable']??false)<a href="{{ route('seller.resource.'.$module.'.edit',array_merge(['id'=>$row['id']],$routeParams)) }}" class="btn btn-sm btn-outline-secondary">Edit</a>@endif</div></td></tr>@empty<tr><td colspan="{{ count($columns)+1 }}" class="seller-table-empty">No matching records were found.</td></tr>@endforelse</tbody></table></div>
@if($paginator->hasPages())<div class="card-footer d-flex align-items-center">{{ $paginator->withQueryString()->links() }}</div>@endif
</div>
@endsection
