@extends('layouts.seller.app')
@section('title', 'Profile & Settings')
@section('content')
<div class="page-header mb-3"><div><div class="page-pretitle">Seller account</div><h2 class="page-title">Profile & Settings</h2></div></div>
<div class="row row-cards"><div class="col-lg-8"><form method="POST" action="{{ route('seller.profile.update') }}" class="card">@csrf @method('PUT')<div class="card-header"><h3 class="card-title">Account and business details</h3></div><div class="card-body"><div class="row g-3">
@foreach ([['name','Name',$user->name,'text'],['email','Email',$user->email,'email'],['mobile','Mobile',$user->mobile,'text'],['business_name','Business name',$seller->business_name,'text'],['legal_name','Legal name',$seller->legal_name,'text'],['trade_license_number','Trade license',$seller->trade_license_number,'text'],['tax_number','Tax number',$seller->tax_number,'text'],['city','City',$seller->city,'text'],['state','Division / state',$seller->state,'text'],['zipcode','Postal code',$seller->zipcode,'text'],['latitude','Latitude',$seller->latitude,'number'],['longitude','Longitude',$seller->longitude,'number']] as $field)<div class="col-md-6"><label class="form-label">{{ $field[1] }}</label><input type="{{ $field[3] }}" step="any" name="{{ $field[0] }}" value="{{ old($field[0],$field[2]) }}" class="form-control" @if(in_array($field[0],['name','email','business_name'])) required @endif></div>@endforeach
<div class="col-12"><label class="form-label">Address</label><textarea name="address" class="form-control" rows="3">{{ old('address',$seller->address) }}</textarea></div></div></div><div class="card-footer text-end"><button class="btn btn-success">Save changes</button></div></form></div>
<div class="col-lg-4"><div class="card mb-3"><div class="card-header"><h3 class="card-title">Business status</h3></div><div class="card-body"><dl class="row"><dt class="col-6">Verification</dt><dd class="col-6"><span class="badge bg-blue-lt">{{ str($seller->verification_status)->replace('_',' ')->title() }}</span></dd><dt class="col-6">Visibility</dt><dd class="col-6">{{ str($seller->visibility_status)->replace('_',' ')->title() }}</dd><dt class="col-6">Commission</dt><dd class="col-6">{{ number_format((float)$seller->commission_rate,2) }}%</dd></dl></div></div><form method="POST" action="{{ route('seller.password.change') }}" class="card">@csrf @method('PUT')<div class="card-header"><h3 class="card-title">Change password</h3></div><div class="card-body"><div class="mb-3"><label class="form-label">Current password</label><input type="password" name="current_password" class="form-control" required></div><div class="mb-3"><label class="form-label">New password</label><input type="password" name="password" class="form-control" required></div><div><label class="form-label">Confirm password</label><input type="password" name="password_confirmation" class="form-control" required></div></div><div class="card-footer"><button class="btn btn-outline-success w-100">Update password</button></div></form></div></div>
@endsection
